#ifndef VULKAN_ERROR_H_
#define VULKAN_ERROR_H_

/**
 * The Vulkan error codes
 */
typedef enum {
    VULKAN_ERR_NONE = 0,
    VULKAN_ERR_INSTANCE,
    VULKAN_ERR_DEVICE,
    VULKAN_ERR_SWAPCHAIN,
    VULKAN_ERR_IMAGE_VIEW,
    VULKAN_ERR_IMAGE,
    VULKAN_ERR_CMD_POOL,
    VULKAN_ERR_CMD_BUF,
    VULKAN_ERR_FENCE,
    VULKAN_ERR_SEMAPHORE,
    VULKAN_ERR_CREATE_DESCRIPTOR_SET_LAYOUT,
    VULKAN_ERR_ALLOCATE_DESCRIPTOR_SETS,
    VULKAN_ERR_CREATE_PIPELINE_LAYOUT,
    VULKAN_ERR_CREATE_SHADER_MODULE,
    VULKAN_ERR_CREATE_COMPUTE_PIPELINES
} vulkan_error_code_t;

#endif // VULKAN_ERROR_H_
